CREATE DATABASE SPRING_MVC2_EX;

USE SPRING_MVC2_EX;

CREATE TABLE T_ORDER_LIST(
	MEMBER_ID 		VARCHAR(30),
	ORDER_ID 	  	VARCHAR(30),
	PRODUCT_CODE 	VARCHAR(30),
	PRODUCT_NAME	VARCHAR(30),
	PRODUCT_PRICE	INT,
	ORDER_COUNT		INT,
	TOTAL_PRICE		INT,
	ORDER_DATE  DATE
);

CREATE TABLE T_PRODUCT_IMAGE(
	PRODUCT_CODE VARCHAR(30),
	IMAGE_NAME 	 VARCHAR(30),
	IMAGE_TYPE 	 VARCHAR(30),
	FILE_SIZE	 VARCHAR(30)
);


INSERT INTO T_ORDER_LIST VALUES("user1","req1","0x001","기계식키보드",37000,1,37000,now());
INSERT INTO T_ORDER_LIST VALUES("user2","req2","0x002","무소음 마우스",24000,3,72000,now());
INSERT INTO T_ORDER_LIST VALUES("user3","req3","0x003","장패드",7000,7,49000,now());

SELECT * FROM T_ORDER_LIST;


CREATE TABLE T_PRODUCT_IMAGE(
	PRODUCT_CODE VARCHAR(30),
	IMAGE_NAME 	 VARCHAR(30),
	IMAGE_TYPE 	 VARCHAR(30),
	FILE_SIZE	 VARCHAR(30)
);
INSERT INTO T_PRODUCT_IMAGE VALUES("0x001" , "keyboard.png" , "png", "4Mb");
INSERT INTO T_PRODUCT_IMAGE VALUES("0x002" , "mouse.jpg"    , "jpg", "3Mb");
INSERT INTO T_PRODUCT_IMAGE VALUES("0x003" , "pad.gif"      , "gif", "2Mb");

SELECT * FROM T_PRODUCT_IMAGE;